In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
styles = ['隸', '楷', '篆', '行', '草']
column_names = ["key", "character", "style", "author", "image"]
image_size = 28

In [14]:
dataframe = pd.read_csv("/tf/hanzi/data.csv", header=None, names = column_names)
authors = dataframe["author"].unique()
dataset_size = dataframe.shape[0]
dataframe

key character style author                              image
0        宀         容     隸    何绍基    宀/容/png/隸/何绍基-87773-256x256.png
1        宀         容     隸  马王堆帛书  宀/容/png/隸/马王堆帛书-87777-256x256.png
2        宀         容     隸    辟雍碑    宀/容/png/隸/辟雍碑-87771-256x256.png
3        宀         容     隸  马王堆帛书  宀/容/png/隸/马王堆帛书-87779-256x256.png
4        宀         容     隸    居延简    宀/容/png/隸/居延简-87774-256x256.png
...     ..       ...   ...    ...                                ...
166666   辰         辰     草    陈道复    辰/辰/png/草/陈道复-27196-256x256.png
166667   辰         辰     草    徐伯清    辰/辰/png/草/徐伯清-27208-256x256.png
166668   辰         辰     草     沈粲     辰/辰/png/草/沈粲-27202-256x256.png
166669   辰         辰     草     怀素     辰/辰/png/草/怀素-27197-256x256.png
166670   辰         辰     草    赵子昂    辰/辰/png/草/赵子昂-27212-256x256.png

[166671 rows x 5 columns]

In [20]:
def get_processed_dataset(fileList, positions):
    dataset = get_raw_dataset(fileList, positions)
    return process_dataset(dataset)

def process_dataset(dataset):
    dataset = dataset.batch(32)
    dataset = dataset.repeat(10)
    return dataset.map(lambda x: (x["image"], x["style"]))

def get_raw_dataset(fileList, positions):
    files = tf.data.Dataset.from_tensor_slices(fileList)
    dataset = files.interleave(tf.data.TextLineDataset, 1)
    return dataset.skip(positions[0]).take(positions[1]).map(parser(), num_parallel_calls=8)

def parser():
    styles_mapping = tf.constant(styles)
    styles_table = tf.contrib.lookup.index_table_from_tensor(mapping=styles_mapping, default_value=-1)
    
    authors_mapping = tf.convert_to_tensor(authors)
    authors_table = tf.contrib.lookup.index_table_from_tensor(mapping=authors_mapping, default_value=-1)
    
    def parse(value):
        nonlocal styles_table, authors_table
        columns_default = [[""], [""], [""], [""], [""]]
        columns = tf.decode_csv(value, record_defaults=columns_default, field_delim=',')
        features = dict(zip(column_names, columns))
        for f, tensor in features.items():
            if f == "style":
                features["style"] = styles_table.lookup(tensor)
            if f == "author":
                features["author"] = authors_table.lookup(tensor)
            if f == "image":
                image_string = tf.read_file(tf.strings.join([tf.constant("/tf/hanzi"), tensor], '/'))
                image_decoded = tf.image.decode_png(image_string, channels=1)
                image_resized = tf.image.resize_images(image_decoded, [image_size, image_size])
                # image_standardized = tf.image.per_image_standardization(image_resized)
                image_reshaped = tf.reshape(image_resized, [image_size, image_size])
                features["image"] = image_reshaped
        return features
    return parse

def get_train_dataset():
    return get_processed_dataset(["/tf/hanzi/shuffled_data.csv"], (0, 120000))

def get_validation_dataset():
    return get_processed_dataset(["/tf/hanzi/shuffled_data.csv"], (120000, 20000))

def get_test_dataset():
    return get_processed_dataset(["/tf/hanzi/shuffled_data.csv"], (140000, dataset_size - 140000))

train_dataset = get_train_dataset()

iterator = train_dataset.make_initializable_iterator()
el = iterator.get_next()
with tf.Session() as sess:
    sess.run(iterator.initializer)
    tf.tables_initializer().run()
    plt.figure(figsize=(image_size, image_size))
    record = sess.run(el)
    for i in range(25):
        plt.subplot(5,5,i+1)
        plt.imshow(record[0][i], cmap=plt.cm.binary)
    plt.show()

AttributeError: module 'tensorflow' has no attribute 'contrib'

In [48]:
def cnn_model_fn(features, labels, mode):
  one_hot_style = tf.one_hot(labels, 5)

  """Model function for CNN."""
  # Input Layer
  input_layer = tf.reshape(features, [-1, image_size, image_size, 1], name = "ReshapeInput")

  # Convolutional Layer #1
  conv1 = tf.layers.conv2d(
      inputs=input_layer,
      filters=32,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)

  # Pooling Layer #1
  pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)

  # Convolutional Layer #2 and Pooling Layer #2
  conv2 = tf.layers.conv2d(
      inputs=pool1,
      filters=64,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)
  pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)

  # Dense Layer
  pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 64])
  dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
  dropout = tf.layers.dropout(inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

  # Logits Layer
  logits = tf.layers.dense(inputs=dropout, units=5)

  predictions = {
      # Generate predictions (for PREDICT and EVAL mode)
      "classes": tf.argmax(input=logits, axis=1),
      # Add `softmax_tensor` to the graph. It is used for PREDICT and by the
      # `logging_hook`.
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
  }

  if mode == tf.estimator.ModeKeys.PREDICT:
    return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

  # Calculate Loss (for both TRAIN and EVAL modes)
  loss = tf.losses.softmax_cross_entropy(one_hot_style, logits=logits)

  # Configure the Training Op (for TRAIN mode)
  if mode == tf.estimator.ModeKeys.TRAIN:
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
    train_op = optimizer.minimize(
        loss=loss,
        global_step=tf.train.get_global_step())
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

  # Add evaluation metrics (for EVAL mode)
  eval_metric_ops = {
      "accuracy": tf.metrics.accuracy(
          labels=labels, predictions=predictions["classes"])
  }
  return tf.estimator.EstimatorSpec(
      mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

In [51]:
style_classifier = tf.estimator.Estimator(
    model_fn=cnn_model_fn
)

tensors_to_log = {"probabilities": "softmax_tensor"}

logging_hook = tf.train.LoggingTensorHook(tensors=tensors_to_log, every_n_iter=50)

style_classifier.train(
    input_fn=get_train_dataset,
    steps=10000,
    hooks=[logging_hook])

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_train_distribute': None, '_save_summary_steps': 100, '_protocol': None, '_num_ps_replicas': 0, '_device_fn': None, '_log_step_count_steps': 100, '_is_chief': True, '_task_type': 'worker', '_tf_random_seed': None, '_model_dir': '/tmp/tmpybklolrl', '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_save_checkpoints_steps': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f469025d588>, '_save_checkpoints_secs': 600, '_task_id': 0, '_eval_distribute': None}
INFO:tensorflow:Calling model_fn.
called
called
called
cnn_model_fn
Tensor("IteratorGetNext:0", shape=(?, 28, 28), dtype=float32)
Tensor("Ite

INFO:tensorflow:global_step/sec: 14.9125
INFO:tensorflow:probabilities = [[0.14754051 0.15687771 0.15317436 0.21480532 0.32760206]
 [0.20417085 0.19192328 0.18747531 0.17579068 0.24063988]
 [0.19320443 0.18720526 0.19014612 0.22069457 0.20874956]
 [0.06316014 0.08587721 0.11855593 0.36312783 0.36927888]
 [0.1956661  0.18436    0.18807037 0.21758522 0.2143183 ]
 [0.19228345 0.18438853 0.18669194 0.22411044 0.21252567]
 [0.0842099  0.04913034 0.04504299 0.37707284 0.444544  ]
 [0.23589733 0.05763238 0.10869285 0.29739243 0.30038497]
 [0.12512921 0.19266447 0.11876824 0.1979713  0.36546677]
 [0.20657344 0.15661395 0.19051374 0.23168933 0.21460949]
 [0.19263043 0.1864874  0.19081958 0.22144493 0.20861763]
 [0.19209503 0.18634929 0.18809776 0.22158505 0.21187286]
 [0.19056009 0.18700017 0.18350022 0.22042596 0.21851356]
 [0.19430639 0.18581566 0.18941699 0.22195676 0.2085042 ]
 [0.10919642 0.17394868 0.15216114 0.24539442 0.31929937]
 [0.03517239 0.01636713 0.05335622 0.48098844 0.41411588]

INFO:tensorflow:loss = 1.4585292, step = 401 (6.186 sec)
INFO:tensorflow:probabilities = [[0.18385564 0.18346198 0.17976579 0.23683728 0.21607935]
 [0.19291306 0.18164845 0.17116587 0.24413437 0.21013825]
 [0.18707982 0.18202442 0.17993629 0.23898566 0.2119738 ]
 [0.01284888 0.0027053  0.00611809 0.83424807 0.14407963]
 [0.08916991 0.03051995 0.02811572 0.6167306  0.23546389]
 [0.09795146 0.04958488 0.04730349 0.42922643 0.37593374]
 [0.1842105  0.17777498 0.17795144 0.23451065 0.22555242]
 [0.16271019 0.12028666 0.06358647 0.29425386 0.3591628 ]
 [0.18813902 0.18341026 0.17676385 0.2359844  0.21570253]
 [0.12092876 0.10401168 0.06621795 0.33312517 0.3757164 ]
 [0.19291143 0.12781385 0.12613109 0.2287198  0.3244239 ]
 [0.15965931 0.18370329 0.14396916 0.21576673 0.2969016 ]
 [0.18337017 0.1852144  0.13982087 0.23845786 0.25313663]
 [0.15064532 0.1605777  0.12773615 0.33041817 0.23062275]
 [0.16334696 0.1329229  0.060103   0.24392635 0.39970076]
 [0.14233951 0.09628008 0.10083685 0.3598

INFO:tensorflow:global_step/sec: 15.7948
INFO:tensorflow:probabilities = [[0.18564472 0.18373321 0.17628624 0.2386857  0.21565011]
 [0.06341527 0.06856566 0.0282746  0.44473696 0.39500755]
 [0.09137053 0.09378068 0.05354867 0.41860473 0.34269533]
 [0.05694363 0.06219215 0.02212941 0.18045317 0.6782816 ]
 [0.1871666  0.18503043 0.16996954 0.24131632 0.21651708]
 [0.18491012 0.18330288 0.17452168 0.24092357 0.2163417 ]
 [0.1890789  0.18240209 0.17313845 0.2400931  0.21528746]
 [0.02539973 0.02713905 0.00999533 0.32568002 0.6117859 ]
 [0.14789456 0.13553949 0.0940411  0.35122868 0.2712962 ]
 [0.02304445 0.02165884 0.00786414 0.642032   0.30540055]
 [0.1859091  0.18034409 0.17196342 0.24496818 0.21681516]
 [0.1724477  0.16201627 0.11974016 0.28506392 0.26073194]
 [0.18733004 0.18664455 0.17271145 0.24002981 0.21328415]
 [0.03425912 0.02041034 0.01065798 0.4038476  0.53082496]
 [0.09040532 0.13878489 0.07992008 0.36320755 0.3276822 ]
 [0.09686921 0.10540877 0.07452098 0.37185228 0.35134882]

INFO:tensorflow:loss = 1.1861906, step = 901 (7.192 sec)
INFO:tensorflow:probabilities = [[0.1832845  0.18122208 0.16494355 0.25030324 0.22024661]
 [0.15986553 0.17398532 0.12135059 0.2854761  0.25932246]
 [0.15525274 0.15505208 0.083589   0.24036512 0.3657411 ]
 [0.16494532 0.15453224 0.14347918 0.2642275  0.27281573]
 [0.03655336 0.03496895 0.03517179 0.3425138  0.55079204]
 [0.05866408 0.05134149 0.02565865 0.55836326 0.30597258]
 [0.11755977 0.14889944 0.03296645 0.15197727 0.5485971 ]
 [0.12928876 0.16607441 0.08172114 0.24003714 0.3828786 ]
 [0.13726525 0.10762707 0.08132362 0.39556405 0.27822   ]
 [0.18140012 0.18407583 0.16515537 0.25201258 0.21735603]
 [0.15964872 0.15537114 0.15844174 0.2576073  0.268931  ]
 [0.1612238  0.18599877 0.11122673 0.18784918 0.35370147]
 [0.03136212 0.03764841 0.01788741 0.56582624 0.34727585]
 [0.1685027  0.08564325 0.06945683 0.32014063 0.3562566 ]
 [0.17480572 0.18085618 0.06694072 0.24389778 0.33349958]
 [0.1253386  0.10291316 0.05981905 0.2826

INFO:tensorflow:global_step/sec: 12.2725
INFO:tensorflow:probabilities = [[0.1844751  0.18614002 0.11090431 0.2460384  0.27244216]
 [0.07986079 0.0540378  0.02047363 0.22749168 0.6181361 ]
 [0.17330013 0.16578333 0.13773589 0.26847094 0.25470966]
 [0.1349552  0.08685529 0.07394692 0.3479405  0.35630208]
 [0.19025429 0.17912094 0.14132997 0.25892603 0.23036873]
 [0.17761889 0.18784378 0.14594275 0.24428321 0.24431138]
 [0.1821021  0.18387958 0.12788817 0.21918656 0.28694353]
 [0.11540967 0.10669921 0.06910844 0.29611734 0.41266534]
 [0.18270475 0.1857218  0.16291873 0.251957   0.21669778]
 [0.04417872 0.02978778 0.00903565 0.40212396 0.5148739 ]
 [0.07409215 0.11029315 0.04456779 0.37650216 0.39454472]
 [0.14908293 0.17915036 0.12898529 0.28617746 0.2566039 ]
 [0.2861398  0.18607576 0.05256578 0.20335653 0.27186212]
 [0.07874472 0.18267457 0.01930563 0.3155079  0.40376717]
 [0.11511996 0.1262961  0.09904151 0.36575988 0.29378253]
 [0.18508226 0.18818541 0.16354498 0.24600728 0.21718009]

INFO:tensorflow:loss = 1.222357, step = 1401 (7.750 sec)
INFO:tensorflow:probabilities = [[0.14071101 0.16014576 0.07340345 0.3227941  0.30294558]
 [0.07755684 0.03292151 0.00744488 0.38501877 0.49705803]
 [0.136156   0.11313727 0.05763173 0.32707953 0.36599544]
 [0.16226797 0.16804974 0.12453793 0.29580444 0.2493399 ]
 [0.04117664 0.03904249 0.01643118 0.4844813  0.41886836]
 [0.2302572  0.13998333 0.04837851 0.28920528 0.2921757 ]
 [0.13816331 0.14983788 0.09806881 0.31136385 0.30256614]
 [0.18156208 0.19516946 0.1605597  0.25185975 0.21084905]
 [0.10325933 0.12355579 0.02657285 0.2573727  0.48923934]
 [0.10970789 0.10888968 0.03635876 0.29517213 0.4498716 ]
 [0.13587503 0.20169036 0.06054574 0.2686296  0.33325922]
 [0.17193909 0.18267298 0.11829305 0.25187626 0.27521867]
 [0.14106895 0.16619433 0.08303512 0.23870899 0.3709926 ]
 [0.08189958 0.16344775 0.02551819 0.41865203 0.31048244]
 [0.01920544 0.01002575 0.01263341 0.41924366 0.53889173]
 [0.15935051 0.19228324 0.10117973 0.2132

INFO:tensorflow:global_step/sec: 12.3616
INFO:tensorflow:probabilities = [[0.0877271  0.12329939 0.03905996 0.4066903  0.3432233 ]
 [0.00724394 0.02967609 0.00203125 0.73514986 0.22589886]
 [0.06462095 0.08667097 0.02063165 0.3942788  0.4337976 ]
 [0.2252737  0.17680097 0.08726093 0.23159997 0.27906445]
 [0.13723296 0.09691215 0.03819385 0.3307653  0.3968957 ]
 [0.21679354 0.17931125 0.07913067 0.18408898 0.34067556]
 [0.05191688 0.06191115 0.01212341 0.37189248 0.5021561 ]
 [0.19375534 0.19195005 0.12336896 0.19626202 0.2946636 ]
 [0.05917647 0.03705104 0.0194923  0.49830437 0.3859758 ]
 [0.05204925 0.03295295 0.015993   0.3578174  0.54118735]
 [0.14692615 0.18660727 0.11232928 0.22250777 0.3316295 ]
 [0.17318925 0.18115309 0.10962228 0.32473955 0.21129581]
 [0.07854859 0.05356242 0.03469172 0.4770121  0.3561852 ]
 [0.17341994 0.19748193 0.15314777 0.26838246 0.20756795]
 [0.0868701  0.10787117 0.07212497 0.3042415  0.42889223]
 [0.0901009  0.12527458 0.03647294 0.23634917 0.51180243]

INFO:tensorflow:loss = 1.3000511, step = 1901 (7.637 sec)
INFO:tensorflow:probabilities = [[0.17729418 0.19751248 0.15967165 0.2541485  0.2113731 ]
 [0.07372185 0.04353442 0.03382114 0.3654617  0.48346087]
 [0.02527057 0.05312217 0.02077213 0.51256555 0.38826954]
 [0.07183071 0.1119498  0.04840598 0.36470824 0.4031053 ]
 [0.10257349 0.03029929 0.00513077 0.5659315  0.29606497]
 [0.04801447 0.0589053  0.01449662 0.31825134 0.56033224]
 [0.17975572 0.19399674 0.14976943 0.23741025 0.23906788]
 [0.14526612 0.14070773 0.06182316 0.35791785 0.2942851 ]
 [0.09862236 0.05431662 0.04115115 0.5409531  0.26495677]
 [0.0793867  0.14526035 0.04696635 0.11007986 0.6183067 ]
 [0.07121184 0.13717447 0.03224466 0.3754755  0.38389358]
 [0.06736248 0.05259218 0.01711525 0.44526866 0.41766143]
 [0.2950515  0.17739047 0.13395241 0.17344359 0.22016203]
 [0.11381043 0.15895708 0.0508292  0.37783793 0.2985654 ]
 [0.18578565 0.21161969 0.11804519 0.26785234 0.21669714]
 [0.07222765 0.04691894 0.04262287 0.530

INFO:tensorflow:global_step/sec: 13.1821
INFO:tensorflow:probabilities = [[0.13324909 0.16127002 0.0161784  0.4517173  0.23758519]
 [0.03331343 0.04752584 0.00250591 0.51460296 0.4020519 ]
 [0.10481706 0.17240323 0.03871028 0.17549673 0.5085727 ]
 [0.04469508 0.03392496 0.01353551 0.4239992  0.48384526]
 [0.0055481  0.00041963 0.00018314 0.21035345 0.7834957 ]
 [0.02751567 0.04774635 0.00298016 0.26437536 0.6573825 ]
 [0.13968873 0.27744853 0.09480867 0.19763133 0.29042277]
 [0.01489261 0.01346544 0.00277607 0.7648168  0.20404907]
 [0.12373593 0.14123759 0.02645954 0.4212348  0.28733212]
 [0.14589345 0.26047096 0.01936875 0.27110928 0.3031575 ]
 [0.23508237 0.24686371 0.02609224 0.1094856  0.38247606]
 [0.14879933 0.46699598 0.00808702 0.10015848 0.27595913]
 [0.19277214 0.25724873 0.04968278 0.23229584 0.2680005 ]
 [0.02577375 0.02618004 0.00515044 0.43752444 0.5053714 ]
 [0.20692554 0.09624045 0.05663572 0.3697758  0.27042255]
 [0.01406109 0.03366883 0.00672859 0.39571935 0.54982215]

INFO:tensorflow:loss = 1.2138683, step = 2401 (7.661 sec)
INFO:tensorflow:probabilities = [[0.07999295 0.37522477 0.03699112 0.32594812 0.1818431 ]
 [0.09222437 0.04374921 0.02923923 0.6294965  0.20529056]
 [0.00170124 0.00110026 0.00273694 0.60100955 0.39345193]
 [0.47950882 0.03997401 0.02781115 0.29913232 0.15357368]
 [0.04319048 0.203576   0.01124259 0.34796023 0.39403066]
 [0.03776767 0.10323662 0.02963838 0.40892923 0.42042816]
 [0.02682251 0.03684274 0.00249896 0.41023088 0.5236049 ]
 [0.05451075 0.01388646 0.0038311  0.78871065 0.13906106]
 [0.8679956  0.08447701 0.00484539 0.0185606  0.02412141]
 [0.0685471  0.08171964 0.05853379 0.5474747  0.24372482]
 [0.02724539 0.08243015 0.00359562 0.6149227  0.27180615]
 [0.04403191 0.01804287 0.02040162 0.4736471  0.44387662]
 [0.15361251 0.11541069 0.08117146 0.33393678 0.31586853]
 [0.04722156 0.16172385 0.01215385 0.44854704 0.33035377]
 [0.21082269 0.1690541  0.084929   0.31181088 0.22338338]
 [0.4331048  0.10464848 0.01095041 0.218

INFO:tensorflow:global_step/sec: 12.6476
INFO:tensorflow:probabilities = [[0.01605813 0.02971338 0.00602794 0.21136676 0.7368338 ]
 [0.01705877 0.04568637 0.00780174 0.34654403 0.5829091 ]
 [0.00989516 0.01990931 0.00641867 0.17465971 0.78911716]
 [0.01739482 0.09600292 0.00556305 0.5233564  0.35768288]
 [0.04712328 0.05771853 0.00952608 0.48824525 0.39738682]
 [0.03377761 0.04455346 0.04369469 0.4560482  0.42192605]
 [0.04620977 0.2836063  0.61920846 0.02500349 0.02597194]
 [0.04089049 0.08475334 0.02833951 0.5706568  0.27535996]
 [0.02872781 0.19440141 0.0147621  0.23284002 0.5292686 ]
 [0.01727782 0.1327921  0.02037797 0.51079875 0.3187533 ]
 [0.6162342  0.1455624  0.11281797 0.09834912 0.02703631]
 [0.07703699 0.3070219  0.03492027 0.28994644 0.29107445]
 [0.00439843 0.06468076 0.00121531 0.2865677  0.64313775]
 [0.2157726  0.24714471 0.09460665 0.19236995 0.25010616]
 [0.00362732 0.03491341 0.00711479 0.20555215 0.7487923 ]
 [0.04730845 0.20431684 0.01712527 0.43910125 0.29214814]

INFO:tensorflow:loss = 0.982636, step = 2901 (8.376 sec)
INFO:tensorflow:probabilities = [[0.00327475 0.0085258  0.00502721 0.3596736  0.6234986 ]
 [0.01514814 0.05090122 0.01395417 0.3632973  0.55669916]
 [0.69130677 0.12677838 0.17701088 0.00387913 0.00102486]
 [0.12561189 0.2235989  0.23919848 0.2856301  0.12596066]
 [0.04272374 0.01725387 0.00754366 0.29711285 0.63536584]
 [0.10358454 0.09685753 0.07534177 0.3069061  0.4173101 ]
 [0.0568212  0.06746866 0.24505538 0.43312588 0.19752885]
 [0.14622529 0.1484322  0.05302575 0.26011953 0.3921972 ]
 [0.00291935 0.02709061 0.00258281 0.50583535 0.46157184]
 [0.04277015 0.04387292 0.1973725  0.49347848 0.22250594]
 [0.00047096 0.00282601 0.00100851 0.42137295 0.57432157]
 [0.0290553  0.0887046  0.02136651 0.34312505 0.5177486 ]
 [0.01189456 0.07327005 0.0418121  0.6326986  0.24032469]
 [0.00267092 0.0186331  0.00382206 0.387304   0.5875699 ]
 [0.05255526 0.07486589 0.20460027 0.21639718 0.45158148]
 [0.14783911 0.09054983 0.00534205 0.2985

INFO:tensorflow:global_step/sec: 12.9341
INFO:tensorflow:probabilities = [[0.00656235 0.17076777 0.00068699 0.5529435  0.26903942]
 [0.24915142 0.18397614 0.0208684  0.39958543 0.14641856]
 [0.00506494 0.01248796 0.00228123 0.4334868  0.5466791 ]
 [0.00958752 0.05855003 0.00164646 0.57250065 0.3577154 ]
 [0.02769006 0.11728103 0.8336687  0.01966912 0.00169103]
 [0.04285607 0.06117749 0.0071363  0.40768728 0.48114285]
 [0.90362984 0.0477948  0.04822934 0.00026516 0.00008093]
 [0.37810686 0.33432975 0.13997047 0.07670888 0.07088404]
 [0.05082554 0.09556448 0.01617519 0.50376165 0.3336731 ]
 [0.09869774 0.15146822 0.02230875 0.43736672 0.2901586 ]
 [0.39273766 0.28358138 0.00711431 0.23882024 0.07774643]
 [0.04270047 0.02006477 0.00694268 0.5353849  0.3949072 ]
 [0.25117788 0.3395432  0.39946634 0.00627428 0.00353836]
 [0.0101544  0.01839028 0.00223616 0.33894596 0.6302732 ]
 [0.00503011 0.00810299 0.00168568 0.507261   0.47792026]
 [0.1639736  0.15679207 0.01955805 0.37043658 0.2892397 ]

INFO:tensorflow:loss = 1.396408, step = 3401 (6.759 sec)
INFO:tensorflow:probabilities = [[0.08249225 0.46455932 0.05212604 0.19127773 0.20954469]
 [0.01259442 0.04727018 0.02356115 0.35119873 0.5653755 ]
 [0.00794079 0.12677543 0.03639633 0.31566733 0.51322013]
 [0.00374026 0.00793463 0.00401435 0.67053807 0.31377274]
 [0.00252518 0.1021421  0.00193043 0.08633167 0.8070706 ]
 [0.02525168 0.19022702 0.02279778 0.40974414 0.35197937]
 [0.00407878 0.03213871 0.00245085 0.7923952  0.16893652]
 [0.04772487 0.05600545 0.00501732 0.3645065  0.52674586]
 [0.03129837 0.07700378 0.06646038 0.4036657  0.42157173]
 [0.04400957 0.04995123 0.00493045 0.54354304 0.35756576]
 [0.00036879 0.00044927 0.00038183 0.04287987 0.9559202 ]
 [0.16088651 0.45770648 0.12572822 0.20241722 0.0532615 ]
 [0.09304809 0.10802842 0.01587758 0.30984762 0.47319826]
 [0.01105514 0.2895472  0.05107956 0.43838555 0.20993257]
 [0.02579179 0.1472818  0.00789339 0.28023857 0.5387945 ]
 [0.10958179 0.18893267 0.05240697 0.2838

INFO:tensorflow:global_step/sec: 14.1902
INFO:tensorflow:probabilities = [[0.18631157 0.2917978  0.40150112 0.08861831 0.03177121]
 [0.352722   0.2534827  0.09669554 0.141325   0.15577477]
 [0.0318636  0.21101552 0.11265661 0.31997773 0.32448658]
 [0.04704696 0.7060449  0.01485156 0.09643676 0.13561983]
 [0.01117907 0.25642443 0.04299865 0.52002746 0.16937038]
 [0.08010259 0.34128466 0.15701327 0.33398563 0.08761384]
 [0.06516437 0.17868026 0.03717353 0.60629666 0.11268513]
 [0.02912534 0.02251378 0.01074077 0.6134003  0.32421985]
 [0.34272146 0.03057151 0.04958951 0.2777834  0.29933417]
 [0.06058116 0.04554991 0.03603712 0.68899775 0.16883412]
 [0.8880919  0.07428453 0.0320042  0.00529691 0.00032233]
 [0.1769927  0.2344475  0.12720749 0.31095436 0.15039794]
 [0.10022182 0.29473963 0.37126756 0.12887022 0.10490067]
 [0.00123361 0.02136693 0.00881155 0.33834735 0.63024056]
 [0.04025531 0.53228307 0.01028442 0.16691257 0.25026456]
 [0.0154529  0.0429422  0.10629111 0.3798454  0.45546842]

INFO:tensorflow:loss = 1.0431423, step = 3901 (6.967 sec)
INFO:tensorflow:probabilities = [[0.07983942 0.14047985 0.30890873 0.22490907 0.24586292]
 [0.00101274 0.0020465  0.0001326  0.7579974  0.2388107 ]
 [0.00154435 0.00147249 0.00112001 0.5416873  0.45417577]
 [0.05686537 0.06913132 0.13304925 0.68814915 0.05280492]
 [0.02551058 0.02852312 0.06204005 0.779834   0.10409218]
 [0.04487073 0.7602313  0.04187718 0.09963455 0.05338624]
 [0.1666588  0.79253805 0.03119509 0.00416511 0.00544283]
 [0.00989038 0.00640131 0.02265162 0.7061778  0.2548789 ]
 [0.06967542 0.5970024  0.01354798 0.1731113  0.14666295]
 [0.00885137 0.1356177  0.00217211 0.78128016 0.07207872]
 [0.00021598 0.00274465 0.00497549 0.38868997 0.60337394]
 [0.03031354 0.779522   0.02766201 0.13086638 0.03163597]
 [0.04116793 0.04832449 0.00647062 0.65291065 0.2511263 ]
 [0.6337832  0.2625885  0.05231601 0.02006826 0.03124392]
 [0.01519232 0.14157504 0.00683023 0.3386127  0.4977897 ]
 [0.01112745 0.21072783 0.0203132  0.377

INFO:tensorflow:global_step/sec: 12.2252
INFO:tensorflow:probabilities = [[0.00668536 0.07077198 0.07036097 0.26140946 0.5907723 ]
 [0.01319197 0.07312823 0.01126608 0.30768636 0.59472734]
 [0.1235728  0.25172332 0.0597001  0.36181056 0.20319323]
 [0.20435268 0.08839472 0.2901646  0.11553468 0.30155328]
 [0.1461878  0.1438075  0.06956065 0.2328797  0.40756437]
 [0.00064168 0.01089338 0.00189605 0.4559219  0.5306469 ]
 [0.03285874 0.08911074 0.083225   0.53493094 0.25987455]
 [0.00899349 0.03705413 0.00100428 0.16848369 0.7844644 ]
 [0.06964657 0.11083831 0.04734952 0.5842317  0.18793397]
 [0.13236482 0.11498661 0.291231   0.33707842 0.12433905]
 [0.00465322 0.05306853 0.01409656 0.2823513  0.6458304 ]
 [0.0866005  0.1712952  0.01630332 0.16011232 0.5656886 ]
 [0.01197667 0.04803702 0.15288137 0.25513914 0.53196585]
 [0.05759022 0.12249081 0.06608932 0.43526205 0.31856757]
 [0.19375043 0.5287109  0.07092299 0.08588965 0.12072605]
 [0.02580194 0.13284543 0.0270435  0.30803    0.5062792 ]

INFO:tensorflow:loss = 1.0188332, step = 4401 (7.159 sec)
INFO:tensorflow:probabilities = [[0.03303422 0.20802668 0.6796073  0.06716195 0.0121699 ]
 [0.0256487  0.075975   0.02689512 0.4403943  0.43108684]
 [0.01619432 0.05374213 0.0890136  0.72409344 0.11695648]
 [0.17743663 0.17644931 0.04447613 0.44127032 0.1603676 ]
 [0.27007613 0.5144542  0.18022044 0.0256211  0.00962815]
 [0.09826105 0.4530225  0.04904233 0.34726617 0.05240785]
 [0.06516288 0.05674997 0.03853956 0.6303556  0.20919198]
 [0.01775196 0.20492882 0.08430249 0.29028502 0.40273175]
 [0.30697432 0.14818892 0.00408076 0.4360263  0.10472965]
 [0.07946311 0.24374299 0.45969367 0.12671567 0.09038454]
 [0.04458788 0.39867154 0.00561038 0.51520073 0.03592946]
 [0.00153577 0.01609911 0.00177953 0.15463269 0.8259529 ]
 [0.03457611 0.10026644 0.04267998 0.29980633 0.5226711 ]
 [0.00198228 0.07901993 0.0149661  0.5009544  0.40307727]
 [0.00299203 0.00366442 0.00344622 0.609083   0.3808144 ]
 [0.10971337 0.16764626 0.03798462 0.278

INFO:tensorflow:global_step/sec: 13.0022
INFO:tensorflow:probabilities = [[0.13875143 0.23148501 0.05306876 0.27126965 0.30542517]
 [0.07859137 0.01512844 0.02381361 0.57868534 0.30378115]
 [0.17252237 0.20713003 0.03351586 0.3006284  0.28620335]
 [0.27141473 0.11965205 0.03344154 0.33382067 0.24167112]
 [0.07378941 0.01045045 0.03347338 0.5789744  0.30331233]
 [0.00140462 0.03569542 0.01682537 0.23674966 0.7093249 ]
 [0.3987341  0.27891034 0.17926066 0.13606478 0.00703005]
 [0.01695495 0.04520325 0.00032756 0.80402064 0.13349356]
 [0.07136018 0.0609712  0.00904732 0.42371517 0.43490618]
 [0.01046501 0.02360434 0.00748771 0.16203666 0.79640627]
 [0.00947736 0.06865295 0.00437365 0.5485492  0.36894688]
 [0.03883128 0.05602313 0.03531754 0.6186856  0.25114253]
 [0.02094233 0.04867844 0.01052887 0.40372962 0.5161208 ]
 [0.620671   0.20175852 0.09711749 0.05657318 0.0238799 ]
 [0.03877387 0.068475   0.02812611 0.48950768 0.3751173 ]
 [0.00428161 0.01340891 0.00416112 0.5124451  0.46570325]

INFO:tensorflow:loss = 0.92384005, step = 4901 (6.617 sec)
INFO:tensorflow:probabilities = [[0.00033509 0.00202426 0.00072746 0.2857942  0.71111894]
 [0.9965229  0.00225818 0.00121654 0.00000105 0.00000131]
 [0.80094856 0.10866413 0.0690171  0.01287698 0.00849324]
 [0.02053274 0.01004581 0.00119404 0.78904074 0.17918667]
 [0.02926033 0.06049319 0.01894533 0.34316632 0.5481348 ]
 [0.01861166 0.0290838  0.01173076 0.43100297 0.5095708 ]
 [0.02692352 0.10861784 0.01097361 0.40024218 0.45324275]
 [0.00109022 0.0073404  0.00280155 0.46011037 0.52865744]
 [0.41739485 0.12436954 0.2189077  0.08247598 0.15685193]
 [0.01753176 0.10012533 0.03515425 0.28902802 0.5581606 ]
 [0.00724754 0.0276409  0.00136588 0.46589512 0.4978505 ]
 [0.16228825 0.08321793 0.00588433 0.38479775 0.36381176]
 [0.00326091 0.01035885 0.00199866 0.40855667 0.5758249 ]
 [0.08516166 0.2905932  0.05552536 0.31653172 0.25218803]
 [0.03247329 0.10836339 0.188117   0.56328017 0.10776619]
 [0.11597113 0.11540136 0.01694718 0.26

INFO:tensorflow:global_step/sec: 15.7146
INFO:tensorflow:probabilities = [[0.05484659 0.05898936 0.09557679 0.39717245 0.39341488]
 [0.15268318 0.39375517 0.36426312 0.07543124 0.01386723]
 [0.00256958 0.00613968 0.08510543 0.23867139 0.66751397]
 [0.497882   0.34196195 0.05677079 0.0964132  0.00697194]
 [0.08472788 0.17357424 0.08584636 0.29406893 0.36178258]
 [0.04165724 0.23496766 0.04456874 0.41440946 0.2643969 ]
 [0.00240577 0.02289309 0.00920057 0.43733227 0.52816826]
 [0.04342547 0.16781665 0.32673228 0.40977108 0.05225451]
 [0.1455297  0.2603076  0.02208413 0.39291275 0.17916584]
 [0.29525337 0.05506825 0.00552509 0.3395386  0.3046147 ]
 [0.00124646 0.00702625 0.00928255 0.3971276  0.5853172 ]
 [0.9284261  0.05224815 0.01932564 0.00000006 0.        ]
 [0.02234877 0.22278124 0.0586448  0.27581078 0.42041433]
 [0.00244277 0.0075981  0.00961163 0.46664295 0.51370454]
 [0.6083824  0.13337654 0.01470829 0.2235337  0.01999918]
 [0.22993386 0.08217198 0.06763302 0.4223004  0.19796072]

INFO:tensorflow:loss = 0.8656488, step = 5401 (6.971 sec)
INFO:tensorflow:probabilities = [[0.00421012 0.00536806 0.00237875 0.43049327 0.55754983]
 [0.93041515 0.03969362 0.02049001 0.00814872 0.0012524 ]
 [0.00321704 0.12199707 0.0169409  0.7103232  0.1475218 ]
 [0.00099251 0.02019589 0.00571878 0.7927181  0.18037476]
 [0.01145016 0.18867649 0.02327645 0.45112878 0.32546812]
 [0.00996353 0.11809114 0.00688659 0.41805184 0.44700694]
 [0.10144538 0.22271228 0.11359224 0.30332226 0.25892782]
 [0.38847998 0.25643077 0.2581147  0.06842706 0.02854751]
 [0.00040699 0.00621546 0.00110722 0.45969212 0.5325782 ]
 [0.02790653 0.08513627 0.04057742 0.4068871  0.4394926 ]
 [0.00066194 0.0119511  0.00163761 0.35211912 0.6336302 ]
 [0.00034663 0.00010335 0.00003068 0.08874391 0.9107754 ]
 [0.41307446 0.5065429  0.05762627 0.02018483 0.00257146]
 [0.00384469 0.00217023 0.0014543  0.85172707 0.14080372]
 [0.07394399 0.22078404 0.01954417 0.37308615 0.3126416 ]
 [0.00375333 0.04390333 0.0292269  0.555

INFO:tensorflow:global_step/sec: 14.1876
INFO:tensorflow:probabilities = [[0.08334232 0.4217984  0.43649894 0.0258215  0.03253887]
 [0.00277897 0.04034524 0.00207274 0.25761092 0.6971922 ]
 [0.0006904  0.00885662 0.00103029 0.41715875 0.57226396]
 [0.02145078 0.14927731 0.00331633 0.4742801  0.3516755 ]
 [0.20735754 0.57566714 0.03117568 0.15127221 0.0345275 ]
 [0.05435756 0.01405802 0.0086032  0.18881136 0.7341698 ]
 [0.08959243 0.11582354 0.00717234 0.39087245 0.39653927]
 [0.15226702 0.5321072  0.02075071 0.20336686 0.09150826]
 [0.01385794 0.01948957 0.0014072  0.35609862 0.6091467 ]
 [0.02228272 0.10505457 0.20438711 0.44031492 0.2279607 ]
 [0.00077257 0.00566099 0.00117051 0.10281879 0.8895772 ]
 [0.0734852  0.79157925 0.06549119 0.06537177 0.00407261]
 [0.00011793 0.01770963 0.00004161 0.12020692 0.8619239 ]
 [0.0021232  0.06289874 0.00065633 0.5228045  0.41151723]
 [0.4101107  0.3380398  0.21060066 0.03316443 0.0080844 ]
 [0.00237239 0.00226068 0.00617728 0.26076698 0.7284226 ]

INFO:tensorflow:loss = 0.8823863, step = 5901 (6.315 sec)
INFO:tensorflow:probabilities = [[0.11983127 0.8668311  0.01259575 0.0007121  0.00002984]
 [0.02799708 0.06679432 0.02029172 0.3435623  0.54135454]
 [0.00043316 0.04070952 0.00065877 0.31004345 0.64815515]
 [0.006361   0.03293943 0.22579792 0.3477103  0.38719139]
 [0.5917384  0.39832056 0.00823126 0.00087557 0.00083424]
 [0.00772416 0.0398603  0.03905872 0.6493423  0.26401442]
 [0.13256031 0.35837555 0.05788092 0.37711877 0.0740645 ]
 [0.06853838 0.45413184 0.01908686 0.38894135 0.06930148]
 [0.00571609 0.04745156 0.00345021 0.62426937 0.31911284]
 [0.04342491 0.27130696 0.002801   0.37235257 0.31011453]
 [0.00008464 0.00201945 0.00000793 0.18588956 0.8119984 ]
 [0.00124502 0.0009726  0.00021503 0.36903512 0.62853223]
 [0.00150912 0.00994448 0.00959083 0.6435366  0.3354189 ]
 [0.00418818 0.01389652 0.00486034 0.52892566 0.44812924]
 [0.01082263 0.0271555  0.0055817  0.71217525 0.24426492]
 [0.01411052 0.06134056 0.00739099 0.877

INFO:tensorflow:global_step/sec: 14.6913
INFO:tensorflow:probabilities = [[0.10308785 0.12914233 0.7170721  0.03907655 0.01162118]
 [0.00906981 0.06999934 0.00998447 0.47018725 0.4407591 ]
 [0.07502198 0.20083651 0.01166431 0.41090664 0.30157053]
 [0.00121376 0.03346499 0.00786755 0.3728764  0.58457726]
 [0.00476951 0.01215745 0.05853983 0.60326123 0.32127196]
 [0.6318836  0.2765292  0.02686121 0.05467111 0.01005475]
 [0.00422368 0.04322905 0.00437394 0.6501272  0.29804608]
 [0.02527113 0.05472375 0.00857788 0.55664617 0.35478106]
 [0.04803556 0.0741341  0.01054591 0.5218012  0.34548324]
 [0.00822196 0.04859778 0.00518262 0.56061    0.37738764]
 [0.47695482 0.15784653 0.32502982 0.02267239 0.01749651]
 [0.00187465 0.0064311  0.01204023 0.09377462 0.8858794 ]
 [0.06160754 0.14656779 0.22371975 0.2432641  0.3248408 ]
 [0.02980943 0.16800813 0.31154203 0.21172385 0.27891654]
 [0.02902949 0.0115885  0.00934671 0.58230543 0.36772984]
 [0.00004847 0.00055368 0.00005814 0.3040986  0.6952411 ]

INFO:tensorflow:loss = 0.58259964, step = 6401 (6.519 sec)
INFO:tensorflow:probabilities = [[0.5832848  0.2885933  0.10650599 0.01251391 0.00910203]
 [0.07893075 0.13543537 0.01558528 0.58769226 0.18235628]
 [0.06275357 0.6885704  0.12167494 0.09333786 0.0336633 ]
 [0.01088411 0.0431202  0.00116795 0.53776306 0.4070647 ]
 [0.5804863  0.38569677 0.02514492 0.00834857 0.00032347]
 [0.00016245 0.00905535 0.00252937 0.36767042 0.62058234]
 [0.0080082  0.02389143 0.03507638 0.16979747 0.76322657]
 [0.35713142 0.18990882 0.01822457 0.3338852  0.10084997]
 [0.01863979 0.04384102 0.00911491 0.2984687  0.6299355 ]
 [0.38706756 0.41200337 0.02865733 0.10050337 0.07176832]
 [0.02457453 0.09709055 0.25628218 0.4158552  0.20619754]
 [0.16093266 0.6269211  0.05627112 0.08620532 0.06966978]
 [0.00531288 0.07020589 0.04286734 0.68030477 0.20130914]
 [0.18229227 0.27625296 0.01099902 0.3908962  0.13955958]
 [0.21235402 0.07294662 0.00414999 0.31295228 0.39759713]
 [0.00095194 0.00066325 0.0002029  0.42

INFO:tensorflow:global_step/sec: 16.1241
INFO:tensorflow:probabilities = [[0.02249976 0.09138256 0.75590074 0.07203194 0.05818503]
 [0.18089604 0.44001696 0.06179541 0.22884524 0.08844637]
 [0.10969366 0.43782637 0.44692147 0.00484452 0.000714  ]
 [0.00023688 0.00295279 0.00529724 0.5646744  0.4268387 ]
 [0.7825762  0.03750498 0.09994184 0.07415012 0.00582682]
 [0.00709557 0.00872685 0.00079134 0.3267885  0.6565978 ]
 [0.00566976 0.00879433 0.0014538  0.3273553  0.65672684]
 [0.00512499 0.05381434 0.00024848 0.33247584 0.6083364 ]
 [0.11159249 0.03521712 0.7933682  0.04223416 0.01758809]
 [0.00011407 0.00550588 0.00056553 0.4162699  0.5775446 ]
 [0.00584591 0.07926798 0.00710602 0.7824502  0.12532991]
 [0.00022474 0.01039581 0.00075401 0.37829062 0.6103348 ]
 [0.98680186 0.00939866 0.00376361 0.00002739 0.00000847]
 [0.31079856 0.35210648 0.06827854 0.22828107 0.04053538]
 [0.04385693 0.03872881 0.00031004 0.35395327 0.563151  ]
 [0.00509496 0.01515124 0.02080334 0.56085676 0.39809367]

INFO:tensorflow:loss = 0.6339323, step = 6901 (6.147 sec)
INFO:tensorflow:probabilities = [[0.0056225  0.43982366 0.02733213 0.3839709  0.1432508 ]
 [0.00191322 0.00855652 0.00481725 0.19146517 0.7932479 ]
 [0.00836278 0.04969455 0.0555056  0.3175793  0.5688578 ]
 [0.00236002 0.00616304 0.00190155 0.06109316 0.9284822 ]
 [0.07224101 0.87347776 0.0165571  0.02993425 0.0077899 ]
 [0.93799937 0.03926392 0.00063783 0.01821624 0.00388265]
 [0.05215953 0.20297758 0.00522762 0.54542285 0.19421239]
 [0.0001453  0.00052814 0.00000103 0.23413946 0.7651861 ]
 [0.01522239 0.1844033  0.02710924 0.411561   0.36170396]
 [0.0006941  0.00289689 0.00083569 0.7366512  0.25892216]
 [0.00063539 0.04393039 0.00090691 0.49628863 0.4582387 ]
 [0.00542463 0.14735301 0.01535198 0.55387235 0.27799806]
 [0.07742979 0.45748904 0.16953841 0.17463374 0.12090896]
 [0.00015531 0.00125187 0.00040715 0.16467436 0.83351135]
 [0.00052144 0.02343914 0.00571207 0.3652313  0.60509604]
 [0.00203346 0.01673838 0.00227817 0.499

INFO:tensorflow:global_step/sec: 16.1148
INFO:tensorflow:probabilities = [[0.06117753 0.25322396 0.680246   0.00494939 0.00040299]
 [0.15340288 0.06913245 0.01116653 0.43679705 0.32950106]
 [0.01651445 0.04450538 0.00579925 0.3122738  0.6209071 ]
 [0.05495388 0.13123547 0.12346265 0.4193014  0.2710466 ]
 [0.00984939 0.08629859 0.00221469 0.5897784  0.31185898]
 [0.0008329  0.00226115 0.00604415 0.3156492  0.67521256]
 [0.03428988 0.01955382 0.00222397 0.19148532 0.75244707]
 [0.00003738 0.00916003 0.00015179 0.41219068 0.57846004]
 [0.00671859 0.01693312 0.00252812 0.39171055 0.5821097 ]
 [0.00297179 0.02424104 0.02592159 0.31951073 0.62735486]
 [0.01174329 0.02979657 0.02547024 0.47748396 0.45550594]
 [0.02381873 0.06684256 0.0016548  0.6039491  0.30373472]
 [0.07825989 0.08398763 0.00173353 0.53455997 0.30145907]
 [0.00202446 0.11072298 0.00584218 0.49202764 0.3893827 ]
 [0.01607611 0.12336363 0.06440872 0.725313   0.07083855]
 [0.0000895  0.00650207 0.00129269 0.49019068 0.50192505]

INFO:tensorflow:loss = 0.73098975, step = 7401 (6.089 sec)
INFO:tensorflow:probabilities = [[0.16875124 0.12732404 0.70371115 0.0002023  0.00001114]
 [0.0627559  0.15760192 0.00165219 0.7015365  0.0764535 ]
 [0.00135821 0.012159   0.03457626 0.2048188  0.7470877 ]
 [0.83952606 0.00905671 0.15128429 0.00008489 0.00004812]
 [0.53932434 0.40988374 0.04937147 0.00124574 0.00017476]
 [0.00152422 0.04998738 0.00553969 0.3572722  0.58567655]
 [0.0003871  0.00679692 0.00062152 0.7600003  0.2321942 ]
 [0.0207195  0.11938471 0.00683571 0.64474    0.20832007]
 [0.02740945 0.22866508 0.11526835 0.3991015  0.22955565]
 [0.02245744 0.00266166 0.00010376 0.48331678 0.4914604 ]
 [0.02283165 0.04800079 0.01112211 0.3521611  0.5658843 ]
 [0.32621616 0.51594704 0.06359912 0.05390942 0.04032826]
 [0.01984787 0.02728934 0.00275563 0.3780456  0.57206154]
 [0.9505657  0.04467861 0.00413139 0.00042943 0.00019491]
 [0.00698615 0.12160002 0.00681912 0.6874318  0.17716292]
 [0.00717824 0.01877969 0.03189312 0.46

INFO:tensorflow:global_step/sec: 16.3143
INFO:tensorflow:probabilities = [[0.00085611 0.0123845  0.00332224 0.5230262  0.46041092]
 [0.03071668 0.09251169 0.01711249 0.65504855 0.20461059]
 [0.00271554 0.02513541 0.00052022 0.72914654 0.2424822 ]
 [0.07033079 0.5985552  0.1122296  0.17687081 0.04201363]
 [0.00207847 0.02139948 0.00763749 0.32610992 0.6427747 ]
 [0.14499319 0.5185288  0.00385362 0.25250363 0.08012066]
 [0.04301511 0.15466847 0.0682217  0.42804223 0.3060525 ]
 [0.9765346  0.02156273 0.00146602 0.00030054 0.00013605]
 [0.0074056  0.37080097 0.0038307  0.30425322 0.3137096 ]
 [0.00055799 0.05274313 0.00017014 0.6788164  0.26771235]
 [0.845913   0.09424704 0.00287324 0.05000985 0.00695692]
 [0.13585202 0.77261037 0.01889478 0.05850706 0.01413564]
 [0.00892287 0.18556465 0.63313943 0.15830766 0.01406538]
 [0.0039802  0.03703479 0.00011512 0.3122693  0.6466006 ]
 [0.00030382 0.0088059  0.00007662 0.61784524 0.3729684 ]
 [0.04055318 0.38637558 0.16397633 0.21169782 0.19739705]

INFO:tensorflow:loss = 0.7907202, step = 7901 (6.732 sec)
INFO:tensorflow:probabilities = [[0.0012571  0.10521048 0.00091425 0.4194392  0.47317898]
 [0.09460669 0.07258563 0.00151184 0.6907541  0.1405417 ]
 [0.00026649 0.00373614 0.00008407 0.73407906 0.26183426]
 [0.01160549 0.6037489  0.00480311 0.24951963 0.13032278]
 [0.03873811 0.06192428 0.0040853  0.5569257  0.33832657]
 [0.9738132  0.02439374 0.00082268 0.00062918 0.00034114]
 [0.0007831  0.01667939 0.00141145 0.1404964  0.84062964]
 [0.06939954 0.92407656 0.00522065 0.00127197 0.00003129]
 [0.00044917 0.00964446 0.00647539 0.37054873 0.61288226]
 [0.0029639  0.07743986 0.00303608 0.43585518 0.48070493]
 [0.00215675 0.00751284 0.00460348 0.24004397 0.74568295]
 [0.9699496  0.01890224 0.00372829 0.00519234 0.00222758]
 [0.00003713 0.00155185 0.00035362 0.26415035 0.7339071 ]
 [0.00436963 0.54544234 0.0035101  0.32989815 0.11677977]
 [0.00062148 0.04755487 0.00153015 0.44942012 0.50087345]
 [0.00193131 0.00436791 0.00652771 0.193

INFO:tensorflow:global_step/sec: 16.0741
INFO:tensorflow:probabilities = [[0.00225382 0.0831916  0.00840497 0.60451794 0.30163157]
 [0.00248882 0.00900647 0.03853704 0.5290711  0.42089668]
 [0.00017134 0.00377938 0.00208314 0.14282233 0.85114384]
 [0.01289711 0.08029491 0.04847913 0.678089   0.18023989]
 [0.00011739 0.00022261 0.00005147 0.20684779 0.7927607 ]
 [0.00134439 0.00231354 0.00017133 0.2225151  0.77365565]
 [0.0011829  0.00747012 0.06686998 0.18747734 0.73699963]
 [0.00007841 0.01126106 0.0420802  0.7483639  0.1982164 ]
 [0.1379396  0.4778517  0.03134688 0.34891275 0.00394906]
 [0.00089375 0.04287784 0.00052906 0.73651135 0.21918803]
 [0.00234833 0.01466915 0.00190341 0.6501131  0.33096606]
 [0.00001933 0.00031281 0.00038704 0.4021676  0.59711325]
 [0.03906025 0.23872396 0.01610974 0.43550774 0.27059826]
 [0.0429279  0.70585465 0.00569119 0.23700827 0.00851803]
 [0.0013232  0.08855434 0.00228637 0.70985866 0.19797742]
 [0.00161558 0.00597952 0.04874264 0.8253498  0.11831237]

INFO:tensorflow:loss = 1.1616315, step = 8401 (5.995 sec)
INFO:tensorflow:probabilities = [[0.04756425 0.31170106 0.00971395 0.38291323 0.24810748]
 [0.00047262 0.00996292 0.00246948 0.7005001  0.2865949 ]
 [0.00000974 0.00290675 0.00008746 0.09962343 0.89737266]
 [0.00054342 0.00349263 0.00126126 0.6228782  0.3718245 ]
 [0.01701536 0.00015008 0.00135144 0.31876886 0.66271424]
 [0.00023325 0.00774877 0.00195156 0.27699748 0.71306896]
 [0.00788842 0.26324734 0.04611127 0.5675268  0.1152262 ]
 [0.00047409 0.00024973 0.00475097 0.39607447 0.5984507 ]
 [0.12412811 0.36110297 0.03727708 0.2611986  0.21629322]
 [0.00027756 0.02012016 0.00639308 0.39556935 0.5776398 ]
 [0.17652118 0.39201874 0.03000386 0.2794396  0.12201662]
 [0.9554059  0.02481183 0.01822468 0.00140472 0.00015287]
 [0.05749802 0.3161232  0.00581453 0.39880776 0.22175649]
 [0.0002479  0.00044617 0.00062709 0.26063338 0.7380455 ]
 [0.01671186 0.04475273 0.41727522 0.47526276 0.04599745]
 [0.19547158 0.19944379 0.02321144 0.215

INFO:tensorflow:global_step/sec: 15.3104
INFO:tensorflow:probabilities = [[0.0035844  0.00240092 0.00068001 0.6178191  0.37551555]
 [0.00725187 0.26659426 0.02070775 0.44195575 0.26349047]
 [0.00021258 0.00237876 0.00132095 0.28740835 0.7086794 ]
 [0.98625356 0.00943947 0.00362994 0.00052068 0.00015622]
 [0.00571911 0.02646684 0.00379486 0.8194903  0.14452879]
 [0.00003535 0.00027594 0.00050695 0.13763064 0.8615511 ]
 [0.00091318 0.0101023  0.00045736 0.38120702 0.6073202 ]
 [0.00212473 0.00134029 0.02759018 0.61730355 0.35164127]
 [0.94238466 0.05201301 0.005355   0.00022211 0.00002532]
 [0.02721664 0.1047774  0.04454459 0.46931165 0.35414967]
 [0.00020177 0.00464015 0.00044634 0.43168145 0.5630303 ]
 [0.00734952 0.04617842 0.01194637 0.19961596 0.7349097 ]
 [0.00064388 0.28783965 0.00714278 0.6094401  0.09493354]
 [0.00046695 0.00695344 0.01099568 0.42610025 0.5554837 ]
 [0.02843431 0.23269132 0.00468403 0.53696424 0.19722605]
 [0.12081309 0.05478603 0.6625314  0.13478851 0.02708093]

INFO:tensorflow:loss = 0.7449689, step = 8901 (6.145 sec)
INFO:tensorflow:probabilities = [[0.00008109 0.00015056 0.00031548 0.03948629 0.95996666]
 [0.00006933 0.00031415 0.00016073 0.07426143 0.9251944 ]
 [0.00304171 0.00619201 0.00112271 0.33096737 0.65867615]
 [0.02423785 0.11004184 0.01639024 0.24844828 0.6008819 ]
 [0.02476303 0.04458777 0.00038446 0.4737173  0.4565474 ]
 [0.01100474 0.19651844 0.06521924 0.39236057 0.33489695]
 [0.03989836 0.62288034 0.0496865  0.2179628  0.06957196]
 [0.00013963 0.00184507 0.00005116 0.12817349 0.8697906 ]
 [0.00056195 0.05330982 0.00062276 0.41396222 0.5315433 ]
 [0.00002683 0.00019604 0.00047463 0.13352276 0.8657797 ]
 [0.04676175 0.8263658  0.11489599 0.01011932 0.00185712]
 [0.00012026 0.01177279 0.00301444 0.09481669 0.89027584]
 [0.00166334 0.13706225 0.00158147 0.44483003 0.41486293]
 [0.02181669 0.20874839 0.02696129 0.3406076  0.40186596]
 [0.00000172 0.00020834 0.00015536 0.08045346 0.91918117]
 [0.04683116 0.09733012 0.00112465 0.628

INFO:tensorflow:global_step/sec: 14.9967
INFO:tensorflow:probabilities = [[0.00216345 0.0037498  0.00283285 0.81845146 0.1728024 ]
 [0.00395772 0.0150844  0.00048749 0.81266516 0.16780527]
 [0.9980494  0.00108069 0.00086918 0.00000088 0.00000001]
 [0.03502621 0.0283866  0.92495507 0.01088752 0.0007446 ]
 [0.4019954  0.05850468 0.00974713 0.3061552  0.22359766]
 [0.17797625 0.32573378 0.00516225 0.34964216 0.14148542]
 [0.00055547 0.01513321 0.08068311 0.7324874  0.17114088]
 [0.00283718 0.17539428 0.01018656 0.615435   0.19614692]
 [0.01116078 0.0953051  0.00021539 0.7892474  0.10407137]
 [0.12060286 0.6775816  0.0625552  0.12737806 0.01188227]
 [0.0000131  0.00001463 0.00000197 0.28920242 0.7107679 ]
 [0.00139534 0.01356301 0.00324427 0.30683234 0.674965  ]
 [0.02151564 0.1515456  0.03539947 0.69099396 0.10054526]
 [0.00002689 0.00069738 0.00099741 0.26370105 0.7345773 ]
 [0.02489213 0.07808502 0.10177036 0.5333752  0.26187733]
 [0.27673575 0.58526397 0.00062756 0.13571852 0.00165419]

INFO:tensorflow:loss = 0.8316697, step = 9401 (6.106 sec)
INFO:tensorflow:probabilities = [[0.00019338 0.00987255 0.00011864 0.35594872 0.6338667 ]
 [0.3756975  0.23850167 0.01149929 0.27243197 0.1018696 ]
 [0.0152901  0.01524277 0.06695939 0.54620624 0.35630155]
 [0.03189051 0.0307453  0.0001908  0.6025863  0.33458698]
 [0.03081332 0.05234063 0.9166195  0.00019315 0.00003349]
 [0.00236707 0.00495192 0.00017512 0.30106932 0.6914366 ]
 [0.99768233 0.00039826 0.0019059  0.00000868 0.00000475]
 [0.98560286 0.01179928 0.00092421 0.00164703 0.00002666]
 [0.01806633 0.14379828 0.01473787 0.66102993 0.16236761]
 [0.01103636 0.16599609 0.08242705 0.60649276 0.13404773]
 [0.5106585  0.2489046  0.00453031 0.21414617 0.02176036]
 [0.00007199 0.00028541 0.00016848 0.33291507 0.66655916]
 [0.1948554  0.11183021 0.69263786 0.00055823 0.00011824]
 [0.00294398 0.02972992 0.00072291 0.30623966 0.6603636 ]
 [0.00115515 0.00236157 0.0003819  0.7206616  0.27543986]
 [0.00816596 0.13927253 0.00046934 0.473

INFO:tensorflow:global_step/sec: 16.3438
INFO:tensorflow:probabilities = [[0.06032816 0.07914349 0.26098406 0.23299612 0.36654824]
 [0.00156578 0.00725921 0.00888386 0.21952423 0.76276696]
 [0.00291334 0.05300454 0.01729468 0.43709442 0.48969302]
 [0.00291427 0.02407819 0.0038497  0.7732999  0.19585793]
 [0.00110206 0.01569472 0.00073583 0.48012692 0.50234044]
 [0.00833215 0.34891725 0.02374807 0.36488873 0.25411373]
 [0.00259488 0.02026992 0.00165257 0.607058   0.3684247 ]
 [0.00124099 0.00209147 0.00002295 0.1636063  0.8330383 ]
 [0.00246811 0.09032438 0.04089286 0.4835971  0.3827175 ]
 [0.00645956 0.0518382  0.00092759 0.6315462  0.3092285 ]
 [0.00004035 0.00033763 0.00004924 0.05914965 0.94042313]
 [0.05959616 0.67197335 0.1544859  0.10466132 0.00928336]
 [0.05063026 0.14153475 0.00583379 0.55541104 0.24659023]
 [0.00164048 0.02102378 0.0167159  0.3958605  0.5647594 ]
 [0.00171218 0.08889241 0.00131618 0.5967695  0.31130978]
 [0.00467527 0.07543295 0.01703804 0.4283086  0.47454518]

INFO:tensorflow:loss = 0.77287257, step = 9901 (6.770 sec)
INFO:tensorflow:probabilities = [[0.01064989 0.27277163 0.68311894 0.02950567 0.00395384]
 [0.02117595 0.39395866 0.00059944 0.4871263  0.09713971]
 [0.02028163 0.1745734  0.5490325  0.1974407  0.05867175]
 [0.01907656 0.72109723 0.00130145 0.21610841 0.04241631]
 [0.02516909 0.4234806  0.00666241 0.5077456  0.03694231]
 [0.06203989 0.42049295 0.02885189 0.44969591 0.03891939]
 [0.14837857 0.02231365 0.00125544 0.47027862 0.35777378]
 [0.00120144 0.00884039 0.00024429 0.6005111  0.3892028 ]
 [0.00973402 0.00244397 0.00035676 0.30943263 0.67803264]
 [0.03775318 0.01379199 0.00105015 0.4847246  0.4626801 ]
 [0.9980702  0.00160451 0.00031955 0.00000532 0.00000038]
 [0.05315563 0.44488287 0.0062393  0.3475552  0.14816703]
 [0.01569215 0.12341502 0.426424   0.33328494 0.10118387]
 [0.00000616 0.00030805 0.00116639 0.40289822 0.59562117]
 [0.01105371 0.5356655  0.00756723 0.31940132 0.12631221]
 [0.03686991 0.2056195  0.1561729  0.45

In [54]:
style_classifier.evaluate(
        input_fn=get_validation_dataset,
        steps=1000)

INFO:tensorflow:Calling model_fn.
called
called
called
cnn_model_fn
Tensor("IteratorGetNext:0", shape=(?, 28, 28), dtype=float32)
Tensor("IteratorGetNext:1", shape=(?,), dtype=int64)
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-03-23T15:54:30Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpybklolrl/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [100/1000]
INFO:tensorflow:Evaluation [200/1000]
INFO:tensorflow:Evaluation [300/1000]
INFO:tensorflow:Finished evaluation at 2019-03-23-15:54:45
INFO:tensorflow:Saving dict for global step 10000: accuracy = 0.7, global_step = 10000, loss = 0.73838174
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10000: /tmp/tmpybklolrl/model.ckpt-10000


{'accuracy': 0.7, 'global_step': 10000, 'loss': 0.73838174}